FROM ghcr.io/dockhippie/alpine:3.18-arm64@sha256:a4bdbbc14ac5d2855327935331617a6e443e25068ad1ec0b80a8552bb5feb279

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk17@testing openjdk17-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
