FROM ghcr.io/dockhippie/alpine:3.23-amd64@sha256:24726e73fb8391d2dbc7f3818c1d126cd5513a58f14b23bb757ee5033ba43175

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk17@testing openjdk17-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
