FROM ghcr.io/dockhippie/alpine:3.20-arm64@sha256:49a4250feb34ac60718d755ecc111ba96db3884185fe7ec5afde9061938c77a2

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk17@testing openjdk17-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
