FROM ghcr.io/dockhippie/alpine:3.20-amd64@sha256:64b748b700732d8f05a3bfbb5731d1b08d0e5333b111eed07b50261afc142de7

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk17@testing openjdk17-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
