FROM ghcr.io/dockhippie/alpine:3.20-amd64@sha256:1f8025bf69f7aaf2f968da04d3ad3aa54161ed86a968b092ecf70980d80fd3c4

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk17@testing openjdk17-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
