FROM ghcr.io/dockhippie/alpine:3.22-arm64@sha256:e87c24096e68acf586839a4782e4e9494c3ee58b14d464b60dd3699c979d5fe5

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk17@testing openjdk17-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
