FROM webhippie/alpine:3.15-arm64@sha256:265a1362fecfe7b3dafcf603970bd43f66a7d250eda69d4fa0784cc87e871c95

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk15@testing openjdk15-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
