FROM webhippie/alpine:3.17-arm64@sha256:45e6697c4c66400abe21ea66e1d32526f1d46c71886078cf1df59a4062fb90c3

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk15@testing openjdk15-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
