FROM webhippie/alpine:3.15-amd64@sha256:a1e9dd1cb5a7c5daeb12583401f9ffd4667686f7663443e92bdb65ef9ab4acbb

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk15@testing openjdk15-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
