FROM webhippie/alpine:3.15-amd64@sha256:c6eb1bdb513853450c142908e73b25684b8412225f3646833792ba9e722ae7a4

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk15@testing openjdk15-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
