FROM webhippie/alpine:3.17-amd64@sha256:81645797d270ed33b115101bdf162bccb0426eaf7d5a40626fbe4664596812aa

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk15@testing openjdk15-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
