FROM webhippie/alpine:3.17-arm64@sha256:e8b199f92de782a0c73444feeb3fc242d3e075433d11d22d19d9676681874093

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk15@testing openjdk15-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
