FROM webhippie/alpine:3.14-arm@sha256:dd4d663480736aca86c365d547b6f8e0b24c234b3fc7cffb276381b37298d2ef

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk14@testing openjdk14-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
