FROM webhippie/alpine:3.14-arm@sha256:0f456239304b61e1ffe87662fd602853d3c09d0b9e7d8fb0abe468ca1b91a80f

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk14@testing openjdk14-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
