FROM webhippie/alpine:3.14-arm64@sha256:6ea39fffcfe8f77e4b4a2eb8e8639d38687d1ab74cf7f03ed8a1c4ba071761e6

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk14@testing openjdk14-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
