FROM webhippie/alpine:3.16-amd64@sha256:ba83d990f34814bb33541b2aafc4035a8b3b73213364b8c9ed1bd905c90ced0a

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk14@testing openjdk14-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
