FROM webhippie/alpine:3.17-amd64@sha256:8d849d651667e9b521da4b7b8dd1fcef8ff6b752b624604e4e3034abc8ebbe57

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk14@testing openjdk14-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
