FROM webhippie/alpine:3.14-arm64@sha256:113ebdd1648036854274c60b2d857a0952f5c7145c0d1aa03d55afb6cba2c4c3

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk12@testing openjdk12-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
