FROM webhippie/alpine:3.16-amd64@sha256:ea4358d568e2892692f2e12d42c8b0c3082d4d7ac361e095e790ef4e3d50ab62

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk12@testing openjdk12-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
