FROM ghcr.io/dockhippie/alpine:3.18-arm64@sha256:c923598aa0b5534cc8365fbb1edd8a38b0a0da3e5d1cf59ebe423d7dcc9b4a05

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk12@testing openjdk12-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
