FROM webhippie/alpine:3.16-amd64@sha256:1fe68bbaba19a82afd95526840a87ca00f531c022e35d932186e8e7778a429ca

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk12@testing openjdk12-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
