FROM webhippie/alpine:3.14-amd64@sha256:6494b53c91155b8894836908914abd5aeb16da59be9b7281670f5c24e8abd1e6

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk12@testing openjdk12-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
