FROM ghcr.io/dockhippie/alpine:3.23-amd64@sha256:ee0aa92278dd45912c5376134b65a6acce898de07db18f8ca6e6c57573deeea9

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk21@testing openjdk21-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
