FROM ghcr.io/dockhippie/alpine:3.23-arm64@sha256:7c1f0b8e892c99b6b9eff6aee45b661fda3b5c03de1f2e906cc5365080ff4d03

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk21@testing openjdk21-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
