FROM ghcr.io/dockhippie/alpine:3.22-arm64@sha256:856d60fd8fa6efb611a576bc2a479309c839b0c89e99a0c0eae0aed435e288d1

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk21@testing openjdk21-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
