FROM ghcr.io/dockhippie/alpine:3.23-amd64@sha256:f46b76b43e17610fd8cf7bd73051711232d5e68b6abbc9609516d33883ea5a0d

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk21@testing openjdk21-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
