FROM ghcr.io/dockhippie/alpine:3.23-arm64@sha256:c959847d9d3983e14846d11fb493cb3c57276af9599b6e748878543779322b52

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk21@testing openjdk21-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
