FROM ghcr.io/dockhippie/alpine:3.22-amd64@sha256:5963cee8e649399873840dda6e96496d0adbc83667c4b73850e8bde5d0354f36

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk21@testing openjdk21-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
