FROM webhippie/alpine:3.16-arm64@sha256:eb15b9c7fa193adb1fbf7999cb3db5fb8a7befe8eb54941b95ae7112589c1df7

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk13@testing openjdk13-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
