FROM webhippie/alpine:3.14-arm64@sha256:f567abfe23719de4a3f6781ec9909d461eb5e33a83357176f6ed5aa09fef4b69

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk13@testing openjdk13-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
