FROM webhippie/alpine:3.15-amd64@sha256:a8250c946c3503d4e55780bd38c6d483dffcbee0433602ffc7114cd7d4dd2200

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk13@testing openjdk13-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
