FROM webhippie/alpine:3.16-amd64@sha256:30081e6ff6ac8c74725560e876b8ce87b85029591e33a55700eea137ab4e15ae

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk13@testing openjdk13-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
