FROM webhippie/alpine:3.14-amd64

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk13@testing openjdk13-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
