FROM webhippie/alpine:3.16-arm64@sha256:468cf79a7c070dbe3f265a752d3d29745cb9445e178d827203e382d3c83ac03d

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk13@testing openjdk13-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
