FROM webhippie/alpine:3.17-amd64@sha256:bdc648efae0e19ec8d0059350ce643733aa820e15146d9dd13bc034a79c6d657

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk16@testing openjdk16-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
