FROM webhippie/alpine:3.14-amd64@sha256:aa37e1d269f40a1c4f5462b03d486273299fb087eae2ec49cefdc4c5ef72e6a1

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk16@testing openjdk16-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
