FROM webhippie/alpine:3.15-arm64@sha256:60c18bb7a0f0706f5ccf62d9266d10a90ed587f5476f41286693fc591781d44f

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk16@testing openjdk16-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
