FROM webhippie/alpine:3.14-amd64@sha256:7281e52d4d18eae5893e8eee6e9f9afad7a049ce118475b5ecafcce09a287b08

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk16@testing openjdk16-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
