FROM webhippie/alpine:3.14-arm64@sha256:766802e056818baca0430a31593caaa492808ee498c413d98c13e8fb5ccc819a

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk16@testing openjdk16-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
