FROM webhippie/alpine:3.15-arm64@sha256:ea19898644ba270d4864b50ab80826c5130806d807e49ce26ba320af564d922a

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk16@testing openjdk16-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
