FROM webhippie/alpine:3.14-arm64@sha256:329d030dd5ac4b01e1a7797d48735dded0e3e1229a54150291d436b49f413a9f

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk9 openjdk9-jre-headless && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
