FROM webhippie/alpine:3.15-arm64@sha256:c598174d87ea82cd386db1626f7b2a57fa8a8297353d0dd96b129a111c3595b5

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk9 openjdk9-jre-headless && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
