FROM webhippie/alpine:3.17-arm64@sha256:3e0653e055fa7ff2af11fc4e43209c050612c542344be4e18931f97fd4e29e3d

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk9 openjdk9-jre-headless && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
