FROM webhippie/alpine:3.15-amd64@sha256:071a620f4c6e217bf695f24ffb100bb582da4bf74bdd5aad21851a887aa3a326

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk9 openjdk9-jre-headless && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
