FROM ghcr.io/dockhippie/alpine:3.18-arm64@sha256:79aa73008d56cd18def708e94b608c65d9477db754c457e7fdd46591aa29dabb

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk18@testing openjdk18-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
