FROM ghcr.io/dockhippie/alpine:3.18-amd64@sha256:833e0ca50cb5175a0744b7f11c39d4449fcfb0df74b530a14f783b0e4cf63d3d

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk18@testing openjdk18-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
