FROM ghcr.io/dockhippie/alpine:3.18-arm64@sha256:27b5d77547856e88cd4f0885bfc19e3d0d6551553f909e7886c947e343c2b076

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk18@testing openjdk18-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
