FROM ghcr.io/dockhippie/alpine:3.17-amd64

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk18@testing openjdk18-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
