FROM ghcr.io/dockhippie/alpine:3.18-amd64@sha256:fc5c37a51c9974a15d1996f8d7ddc613764c31d69391c0a4f06ae094e596a03f

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk18@testing openjdk18-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
