FROM webhippie/alpine:3.16-amd64@sha256:ab63842c5232aa8b9ebff72185579a162190cbed568e2bee9eb996d86ab2ca43

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk11 openjdk11 && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
