FROM ghcr.io/dockhippie/alpine:3.20-amd64@sha256:071cdb5c65a05290036c8f72f2564a472163ddc2b6f82eccbb43811bfdeae6e9

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk11 openjdk11 && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
