FROM webhippie/alpine:3.16-arm64@sha256:20a51c65ab222901a60721a1a51bae7243cdabe44b5232121be2d39e0504282a

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk11 openjdk11 && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
