FROM webhippie/alpine:3.14-amd64@sha256:e9458d7ab44f2907eeab4cad9bc0827a16c1ea1d38d386f0575094c092c7db2f

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk11 openjdk11 && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
