FROM ghcr.io/dockhippie/alpine:3.23-arm64@sha256:2c0d4be202497228140ca2c8ab816fc8458745cd0595310eb2e88f553bec6861

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk11 openjdk11 && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
