FROM ghcr.io/dockhippie/alpine:3.18-arm64@sha256:ebc03e902afd77e37ad3bd3e14248949368f04d15b0f399dc42426fb2316684e

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk16@testing openjdk16-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
