FROM webhippie/alpine:3.16-arm64@sha256:97a5ea081775d05a364d8aad9a96ec91cc567f76f65a77d82f777630133fc777

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk10 openjdk10-jre-headless && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
