FROM ghcr.io/dockhippie/alpine:3.18-arm64@sha256:7540f0f6a0305d2c9d4660a531a12ca2664d6cd49ae689d048787d40cd30c03d

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk10 openjdk10-jre-headless && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
