FROM webhippie/alpine:3.16-arm64@sha256:903bac87acbfeedb70f84c5e54bc7e502421a076c472ac5ffc790b26e2712f30

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk10 openjdk10-jre-headless && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
