FROM ghcr.io/dockhippie/alpine:3.18-amd64@sha256:3179395641f0046de185f06dc4f08c9dd76ee320c9dab247864a5dd09f1809df

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk10 openjdk10-jre-headless && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
