FROM ghcr.io/dockhippie/alpine:3.17-amd64@sha256:c8e795285840919b78c25eac33d382078bec564aebb0808f8e8cf9c650f08f39

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk10 openjdk10-jre-headless && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
