FROM ghcr.io/dockhippie/alpine:3.22-amd64@sha256:3bb24cc9ebf3b37c76b3990a4431b9cda40f9b97a0e0252c666892e5ff5caddb

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk11 openjdk11-jre-headless && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
