FROM ghcr.io/dockhippie/alpine:3.20-arm64@sha256:fabfddc15401311e777b4b602ad79d0fddc7e6fb4b4dc4f7cff12d83b208e004

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk11 openjdk11-jre-headless && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
