FROM ghcr.io/dockhippie/alpine:3.23-arm64@sha256:9cc04793dfb9c721b9ba68a90c140ce82ca23579902cc4b3ca198adeacc7c078

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk11 openjdk11-jre-headless && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
