FROM ghcr.io/dockhippie/alpine:3.23-arm64@sha256:70887229b9a439b81617e6487bafed47cc4f2a68b1474dbe5d973111a425f949

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk11 openjdk11-jre-headless && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
