FROM ghcr.io/dockhippie/alpine:3.21-amd64@sha256:8708660135f98a5732f9a34efca97e4884d77fed3e6e68fd3351099bf36b67aa

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk11 openjdk11-jre-headless && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
