FROM ghcr.io/dockhippie/alpine:3.23-amd64@sha256:7cfad1e49d296f82ba46a5965fd25580f5ea9871211014bd00542c34cfe14c80

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk11 openjdk11-jre-headless && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
