FROM webhippie/alpine:3.15-arm64@sha256:02be68d0c89f485e7c311a76091f9fe787051a7f6c1f6573a83c64cdbb773089

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk7 openjdk7-jre-lib && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
