FROM webhippie/alpine:3.14-amd64@sha256:adf8fbaa9f578b2afbad9b282de6eeeb82284a6be430e238811f0fc71727f45f

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk7 openjdk7-jre-lib && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
