FROM webhippie/alpine:3.14-arm@sha256:76d36e7f061af79c4fc213208119e675eee980e4e89334381fc627b60405aac0

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk7 openjdk7-jre-lib && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
