FROM webhippie/alpine:3.16-arm64@sha256:e284557684eb3c267cd7f1e1cf304321ad8f75bc2eefc52d1726b8c1fa24fda2

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk7 openjdk7-jre-lib && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
