FROM webhippie/alpine:3.17-arm@sha256:e32eb094b1d4c7e8204df7d0bff20f6d01e11c060035fd0a49a87228698f6978

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk7 openjdk7-jre-lib && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
