FROM webhippie/alpine:3.16-arm@sha256:2def477e6e289852ad67855a92dcaeeac60c242e180c8a8fdf0c823701b939bb

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk7 openjdk7-jre-lib && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
