FROM webhippie/alpine:latest-arm32v6

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Java" \
  org.label-schema.version="7" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

WORKDIR /srv/app
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["bash"]

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk7 openjdk7-jre-lib && \
  rm -rf /var/cache/apk/*

COPY ./overlay ./overlay-arm32v6 /
