FROM webhippie/alpine:3.15-amd64@sha256:d5f50316392b5f9ec198e807b539759941fb00ea593bf9230fcf653f80427885

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk7 openjdk7-jre-lib && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
