FROM ghcr.io/dockhippie/alpine:3.18-arm@sha256:4b500630ef4835a3e77958ef0e106940109f50ecf1f59ddf997d29e9d5a9898e

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk8 openjdk8-jre-lib && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
