FROM ghcr.io/dockhippie/alpine:3.22-arm64@sha256:06fe5426aa724a77be5fa00f04cc38c7269b5254ba941b2786fbd95b5d887aea

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk8 openjdk8-jre-lib && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
