FROM ghcr.io/dockhippie/alpine:3.23-arm64@sha256:f446f32e1ecf423212ac1261edcab2d10083fb5452126906d7c70382de9c3032

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk8 openjdk8-jre-lib && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
