FROM ghcr.io/dockhippie/alpine:3.20-arm@sha256:46bf8747c4d941776260aaa527ec2e8accd0d30ddc8e91f0dc897b0a91f188a6

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk8 openjdk8-jre-lib && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
