FROM ghcr.io/dockhippie/alpine:3.21-arm@sha256:5100ff1a797378644a41b2fa6615957925e0fbf92bc0da9fd4a514ec35da56cc

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk8 openjdk8-jre-lib && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
