FROM ghcr.io/dockhippie/alpine:3.23-amd64@sha256:02e10204cb0ac3d1dfd0bc8a588b27b5ff3f45437687812715cf526e690956f2

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk8 openjdk8-jre-lib && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
