FROM ghcr.io/dockhippie/alpine:3.23-amd64@sha256:28c9e30e15c5cc2fa020facc2785a4f3b9633e72c82cf9e3a6b5abbbe96bed21

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk8 openjdk8-jre-lib && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
