FROM ghcr.io/dockhippie/alpine:3.23-arm64@sha256:a315f113b1b87f2552175e9d73be99274b9f04695b9b2df9f2be86a5f3407996

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk8 openjdk8-jre-lib && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
