FROM webhippie/alpine:3.17-arm64@sha256:d0a50cab635344260569c81debd0e702949f8ca1b5ac578f97a4cb0995e8fadd

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk19@testing openjdk19-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
