FROM ghcr.io/dockhippie/alpine:3.17-arm64@sha256:f57452ba31d8d2bbba1c61ddf36239a458fc93ccd7126eaa95d2292f3e95cb90

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk19@testing openjdk19-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
