FROM ghcr.io/dockhippie/alpine:3.18-arm64@sha256:8e5099f0d1ada88112e1d61fdaf6047d6d9971b859d5c7088ed86799801dda3f

WORKDIR /srv/app

RUN apk update && \
  apk upgrade && \
  apk add nss openjdk19@testing openjdk19-jre-headless@testing && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
